# masterip  需要修改 master角色的IP 
masterip: 192.168.0.2
# masterport 默认不需要改  master角色的监听端口  如果没有端口冲突，
masterport: 8282
# mode  默认不需要改  模式: http 或 tcp ，如果客户环境可以使用ssh协议，推荐使用http，如果不支持ssh，推荐使用 tcp
mode: http
#  remotepath 远程路径 默认路径为tmp
remotepath: /tmp/
# 磁盘性能检测 none all custom 
disk: 
  type: none
  # 测试的文件路径
  diskcheckpath: /tmp/aaaa
# host 除部署节点以外其他要收集的机器信息
host:
  - ip: 192.168.0.3
    user: root
    password: asdasdad
    #默认可以不添加
    sshport: 22
    diskcheck: enable
    diskcheckpath: /tmp/bbbb
  - ip: 192.168.0.4
    user: root
    password: asdasdasd
  - ip: 192.168.0.5
    user: root
    password: asdasdasd
    diskcheck: disable